---
# software install
- name: ensure jenkins slave is at the latest version
  apt: pkg=jenkins-slave state=latest update_cache=yes
  notify:
  - restart jenkins slave

# software configuration, adds URL & secret
- name: add jenkins slave cli configuration file with secret
  template: >
    dest=/etc/default/jenkins-slave
    src=jenkins-slave.j2
    mode=0644
  when: secret is defined
  register: has_secret
  with_items:
    - "{{ secret }}"
  notify:
  - restart jenkins slave

- name: add jenkins slave cli configuration file
  template: >
    dest=/etc/default/jenkins-slave
    src=jenkins-slave.j2
    mode=0644
  when: secret is not defined
  notify:
  - restart jenkins slave

- name: ensure jenkins is not running to update home directory
  service:
    name: jenkins-slave
    state: stopped
  notify:
  - restart jenkins slave

- name: ensure jenkins user home is /var/lib/jenkins
  user:
    createhome: no
    home: /var/lib/jenkins
    move_home: yes
    name: jenkins
  notify:
  - restart jenkins slave


# credentials (Move to use aws_cli)
- include: aws.yml
  when: jenkins_aws_access is defined and jenkins_aws_secret is defined
